import re
import os
import requests

def cleanup_indexed_issues(dbi_paths: list[str]):
    """Removes blocks from the given DBI files that correspond to issues already indexed in Inducks."""
    
    issue_codes_to_check = set()
    file_blocks = {}
    
    def parse_issue_code_from_block(block: str) -> str:
        m = re.search(r'\[entrycode:([^\]]+)\]', block)
        if m:
            ec = m.group(1).strip()
            if ec.endswith('a'):
                return ec[:-1].strip()
            return ec

        for line in block.split('\n'):
            line = line.strip()
            if not line or line.startswith('^^'):
                continue
            if ' h3 ' in line:
                code_part = line.split(' h3 ')[0].strip()
                if code_part != '->':
                    return code_part
        return ""

    for path in dbi_paths:
        if not os.path.exists(path):
            continue
        try:
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            content = re.sub(r'^\^\^\s*Pre-index.*?\n', '', content, flags=re.MULTILINE)
            blocks = re.split(r'(?=\^\^ Source:)', content)
            
            parsed_blocks = []
            for b in blocks:
                b_str = b.strip()
                if b_str and "^^ Source:" in b_str:
                    lines = [line.rstrip() for line in b_str.split('\n')]
                    cleaned_block = '\n'.join(lines)
                    code = parse_issue_code_from_block(cleaned_block)
                    parsed_blocks.append((code, cleaned_block))
                    if code:
                        issue_codes_to_check.add(code)
            file_blocks[path] = parsed_blocks
        except Exception as e:
            print(f"  [warn] Failed to read {path} for cleanup: {e}")

    if not issue_codes_to_check:
        return

    search_set = {code.replace(" ", "").lower() for code in issue_codes_to_check}
    found_codes = set()
    
    print(f"  [DBI] Checking {len(search_set)} issue(s) against Inducks ISV...")
    try:
        r = requests.get('https://inducks.org/inducks/isv/inducks_issue.isv', stream=True, timeout=15)
        r.raise_for_status()
        for line in r.iter_lines():
            if not search_set:
                break
            parts = line.split(b'^')
            if len(parts) > 11:
                isv_pub = parts[2].decode('utf-8', errors='ignore').replace(' ', '').lower()
                isv_num = parts[3].decode('utf-8', errors='ignore').replace(' ', '').lower()
                isv_full = isv_pub + isv_num
                isv_short = isv_pub.split('/')[-1] + isv_num if '/' in isv_pub else isv_full
                fully_indexed = parts[11].decode('utf-8', errors='ignore').strip().upper()
                
                if fully_indexed == 'Y':
                    to_remove = []
                    for code in search_set:
                        if code == isv_full or code == isv_short or (isv_pub.endswith(code) and not isv_num):
                            found_codes.add(code)
                            to_remove.append(code)
                    for c in to_remove:
                        search_set.remove(c)
    except Exception as e:
        print(f"  [warn] ISV fetch failed: {e}")
        return

    if not found_codes:
        return

    def delete_cover_for_issue(issue_code: str, country_prefix: str):
        m = re.match(r'^([a-zA-Z]+)(\s+)(.*)$', issue_code)
        if m:
            pub_code = m.group(1).lower()
            number = re.sub(r'[^a-zA-Z0-9]', '_', m.group(3)).lower()
            safe_code = f"{pub_code}_{number.zfill(4)}"
        else:
            safe_code = re.sub(r'[^a-zA-Z0-9]', '_', issue_code).lower()
            
        # Check standard .jpg extension
        cover_path = os.path.join("covers", f"{country_prefix}_{safe_code}a_001.jpg")
        if os.path.exists(cover_path):
            try:
                os.remove(cover_path)
                print(f"  [Clean] Deleted cover image {os.path.basename(cover_path)}")
            except Exception as e:
                print(f"  [warn] Failed to delete cover {cover_path}: {e}")

    for path, parsed_blocks in file_blocks.items():
        kept_blocks = []
        country_prefix = os.path.basename(path).replace(".dbi", "").lower()
        
        for code, block in parsed_blocks:
            clean_code = code.replace(" ", "").lower() if code else ""
            if clean_code not in found_codes:
                kept_blocks.append(block)
            else:
                print(f"  [DBI] Issue {code} is already in Inducks. Removing from {path}.")
                delete_cover_for_issue(code, country_prefix)
        
        if len(kept_blocks) < len(parsed_blocks):
            header = "^^ Pre-index automatically generated by DisneyComicsWatcher\n\n"
            sorted_content = header + "\n\n".join(kept_blocks) + "\n\n"
            try:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(sorted_content)
            except Exception as e:
                print(f"  [warn] Failed to rewrite {path}: {e}")

# ─────────────────────────────────────────────────────────────────────────────
#  Public Entry Point
# ─────────────────────────────────────────────────────────────────────────────